export type AreaTag =
  | "全国"
  | "北海道"
  | "東北"
  | "関東"
  | "中部"
  | "関西"
  | "中国・四国"
  | "九州"
  | "沖縄";

export type TravelBudgetTag = "〜2万" | "2〜5万" | "5万〜";
export type TravelDurationTag = "日帰り" | "1泊2日" | "2泊3日" | "それ以上";
export type TravelStyleTag =
  | "グルメ"
  | "自然"
  | "温泉"
  | "歴史・文化"
  | "アクティビティ"
  | "都市観光";

export type DartStyleId =
  | "pin"
  | "dart"
  | "lightning"
  | "sakura"
  | "fire"
  | "airplane";

export type Destination = {
  prefecture: string;
  region: string;
  season: string;
  budget: string;
  highlight: string;
  x: number;
  y: number;
  areas: AreaTag[];
  budgetTags: TravelBudgetTag[];
  durationTags: TravelDurationTag[];
  styleTags: TravelStyleTag[];
};

export type DartStyleOption = {
  id: DartStyleId;
  label: string;
  emoji: string;
};

export const AREA_OPTIONS: AreaTag[] = [
  "全国",
  "北海道",
  "東北",
  "関東",
  "中部",
  "関西",
  "中国・四国",
  "九州",
  "沖縄",
];

export const BUDGET_OPTIONS: TravelBudgetTag[] = ["〜2万", "2〜5万", "5万〜"];
export const DURATION_OPTIONS: TravelDurationTag[] = [
  "日帰り",
  "1泊2日",
  "2泊3日",
  "それ以上",
];
export const STYLE_OPTIONS: TravelStyleTag[] = [
  "グルメ",
  "自然",
  "温泉",
  "歴史・文化",
  "アクティビティ",
  "都市観光",
];

export const DART_STYLES: DartStyleOption[] = [
  { id: "pin", label: "ピン", emoji: "📍" },
  { id: "dart", label: "ダーツ", emoji: "🎯" },
  { id: "lightning", label: "稲妻", emoji: "⚡" },
  { id: "sakura", label: "さくら", emoji: "🌸" },
  { id: "fire", label: "炎", emoji: "🔥" },
  { id: "airplane", label: "飛行機", emoji: "✈️" },
];

export const destinations: Destination[] = [
  {
    prefecture: "北海道",
    region: "北海道地方",
    season: "夏のラベンダーと冬の雪景色",
    budget: "45,000円前後",
    highlight: "富良野の花畑から札幌グルメまで、スケールの大きな景色を一気に楽しめます。",
    x: 0.8,
    y: 0.12,
    areas: ["北海道"],
    budgetTags: ["2〜5万", "5万〜"],
    durationTags: ["2泊3日", "それ以上"],
    styleTags: ["グルメ", "自然", "アクティビティ"],
  },
  {
    prefecture: "青森県",
    region: "東北地方",
    season: "夏祭りと秋のりんごシーズン",
    budget: "28,000円前後",
    highlight: "ねぶたの熱気と奥入瀬渓流の涼やかな自然が一緒に味わえます。",
    x: 0.79,
    y: 0.27,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "歴史・文化", "グルメ"],
  },
  {
    prefecture: "岩手県",
    region: "東北地方",
    season: "新緑から紅葉にかけて",
    budget: "26,000円前後",
    highlight: "平泉の世界遺産と三陸海岸のダイナミックな海景が魅力です。",
    x: 0.83,
    y: 0.31,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "歴史・文化"],
  },
  {
    prefecture: "宮城県",
    region: "東北地方",
    season: "初夏から秋",
    budget: "25,000円前後",
    highlight: "松島の絶景と仙台名物を気軽に組み合わせやすい旅先です。",
    x: 0.8,
    y: 0.35,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["グルメ", "自然", "都市観光"],
  },
  {
    prefecture: "秋田県",
    region: "東北地方",
    season: "秋田竿燈まつりの夏と雪見温泉の冬",
    budget: "27,000円前後",
    highlight: "乳頭温泉郷での湯めぐりと、郷土料理のきりたんぽが待っています。",
    x: 0.74,
    y: 0.31,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["温泉", "自然", "グルメ"],
  },
  {
    prefecture: "山形県",
    region: "東北地方",
    season: "さくらんぼの初夏と蔵王樹氷の冬",
    budget: "24,000円前後",
    highlight: "果樹園めぐりから山寺の静けさまで、和の余韻が濃い県です。",
    x: 0.73,
    y: 0.36,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "歴史・文化", "グルメ"],
  },
  {
    prefecture: "福島県",
    region: "東北地方",
    season: "春の花見山と秋の磐梯高原",
    budget: "23,000円前後",
    highlight: "会津の城下町と五色沼の神秘的な景色を両取りできます。",
    x: 0.77,
    y: 0.41,
    areas: ["東北"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "歴史・文化", "温泉"],
  },
  {
    prefecture: "茨城県",
    region: "関東地方",
    season: "ネモフィラが咲く春",
    budget: "18,000円前後",
    highlight: "ひたち海浜公園の青い丘と海沿いグルメで爽快な気分転換になります。",
    x: 0.79,
    y: 0.47,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
  {
    prefecture: "栃木県",
    region: "関東地方",
    season: "紅葉と冬の温泉",
    budget: "20,000円前後",
    highlight: "日光東照宮の荘厳さと鬼怒川の温泉時間が好相性です。",
    x: 0.75,
    y: 0.46,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["温泉", "歴史・文化", "自然"],
  },
  {
    prefecture: "群馬県",
    region: "関東地方",
    season: "通年の温泉旅",
    budget: "19,000円前後",
    highlight: "草津や伊香保など、湯の個性で選べる温泉好き向けの王道です。",
    x: 0.7,
    y: 0.46,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["温泉", "自然"],
  },
  {
    prefecture: "埼玉県",
    region: "関東地方",
    season: "秋の川越さんぽ",
    budget: "16,000円前後",
    highlight: "小江戸・川越の食べ歩きと秩父の自然で近場でも旅気分が濃く出ます。",
    x: 0.71,
    y: 0.5,
    areas: ["関東"],
    budgetTags: ["〜2万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "歴史・文化", "自然"],
  },
  {
    prefecture: "千葉県",
    region: "関東地方",
    season: "春から初夏の海辺ドライブ",
    budget: "18,000円前後",
    highlight: "海鮮、灯台、のんびりした海辺の景色で気負わない旅ができます。",
    x: 0.78,
    y: 0.53,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "自然", "アクティビティ"],
  },
  {
    prefecture: "東京都",
    region: "関東地方",
    season: "通年",
    budget: "22,000円前後",
    highlight: "最新カルチャーと下町情緒が同居し、短時間でも密度の高い旅になります。",
    x: 0.74,
    y: 0.53,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万", "5万〜"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["都市観光", "グルメ", "歴史・文化"],
  },
  {
    prefecture: "神奈川県",
    region: "関東地方",
    season: "海風が気持ちいい春と秋",
    budget: "20,000円前後",
    highlight: "横浜の夜景、鎌倉の寺社、箱根の温泉を一県で楽しめる万能型です。",
    x: 0.71,
    y: 0.56,
    areas: ["関東"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["都市観光", "温泉", "歴史・文化"],
  },
  {
    prefecture: "新潟県",
    region: "中部地方",
    season: "米どころの秋と雪景色の冬",
    budget: "24,000円前後",
    highlight: "日本海の海鮮、酒蔵、越後湯沢のリゾート感がぎゅっと詰まっています。",
    x: 0.68,
    y: 0.39,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["グルメ", "温泉", "自然"],
  },
  {
    prefecture: "富山県",
    region: "中部地方",
    season: "春の立山黒部と冬の海鮮",
    budget: "25,000円前後",
    highlight: "立山連峰の迫力と富山湾の幸で、景色も食も満足度が高い県です。",
    x: 0.62,
    y: 0.45,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
  {
    prefecture: "石川県",
    region: "中部地方",
    season: "秋から冬の金沢さんぽ",
    budget: "30,000円前後",
    highlight: "兼六園や近江町市場など、歩いて楽しい王道の和旅が楽しめます。",
    x: 0.58,
    y: 0.46,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "グルメ", "都市観光"],
  },
  {
    prefecture: "福井県",
    region: "中部地方",
    season: "春から秋",
    budget: "24,000円前後",
    highlight: "東尋坊の海風と恐竜博物館の遊び心で、ちょっと意外性のある旅になります。",
    x: 0.57,
    y: 0.5,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "アクティビティ", "歴史・文化"],
  },
  {
    prefecture: "山梨県",
    region: "中部地方",
    season: "富士山が澄む秋から冬",
    budget: "22,000円前後",
    highlight: "富士五湖の絶景とワイナリーめぐりで大人っぽい旅が叶います。",
    x: 0.67,
    y: 0.54,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["自然", "温泉", "グルメ"],
  },
  {
    prefecture: "長野県",
    region: "中部地方",
    season: "避暑の夏と紅葉の秋",
    budget: "26,000円前後",
    highlight: "山岳リゾート、温泉、古い町並みまで、旅の欲張りセットみたいな県です。",
    x: 0.65,
    y: 0.48,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日", "それ以上"],
    styleTags: ["自然", "温泉", "アクティビティ"],
  },
  {
    prefecture: "岐阜県",
    region: "中部地方",
    season: "白川郷の冬と高山の春秋",
    budget: "27,000円前後",
    highlight: "合掌造りの景観と飛騨牛のごほうび感で旅情がしっかり深まります。",
    x: 0.58,
    y: 0.55,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "グルメ", "自然"],
  },
  {
    prefecture: "静岡県",
    region: "中部地方",
    season: "海も山も気持ちいい春",
    budget: "23,000円前後",
    highlight: "富士山ビュー、温泉、海鮮が揃っていて、ゆったりもアクティブも選べます。",
    x: 0.69,
    y: 0.59,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["自然", "温泉", "グルメ"],
  },
  {
    prefecture: "愛知県",
    region: "中部地方",
    season: "食と街歩きが楽しい秋",
    budget: "22,000円前後",
    highlight: "名古屋めしを軸に、城下町や海辺の町まで幅広く遊べます。",
    x: 0.61,
    y: 0.6,
    areas: ["中部"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "都市観光", "歴史・文化"],
  },
  {
    prefecture: "三重県",
    region: "近畿地方",
    season: "伊勢神宮が心地よい春秋",
    budget: "24,000円前後",
    highlight: "伊勢志摩の海と参道グルメで、清々しいご褒美旅になります。",
    x: 0.56,
    y: 0.62,
    areas: ["関西"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "グルメ", "自然"],
  },
  {
    prefecture: "滋賀県",
    region: "近畿地方",
    season: "湖風が気持ちいい春から初夏",
    budget: "20,000円前後",
    highlight: "琵琶湖の景色と彦根城の城下町散策で穏やかな時間が流れます。",
    x: 0.54,
    y: 0.56,
    areas: ["関西"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["自然", "歴史・文化"],
  },
  {
    prefecture: "京都府",
    region: "近畿地方",
    season: "桜の春と紅葉の秋",
    budget: "28,000円前後",
    highlight: "寺社、路地、和菓子、朝の静けさまで、旅の余白が美しい街です。",
    x: 0.51,
    y: 0.55,
    areas: ["関西"],
    budgetTags: ["2〜5万", "5万〜"],
    durationTags: ["日帰り", "1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "グルメ", "都市観光"],
  },
  {
    prefecture: "大阪府",
    region: "近畿地方",
    season: "食べ歩きが楽しい通年",
    budget: "23,000円前後",
    highlight: "道頓堀のにぎわいから中之島の洗練まで、テンポ良く遊べる都市旅です。",
    x: 0.5,
    y: 0.58,
    areas: ["関西"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "都市観光"],
  },
  {
    prefecture: "兵庫県",
    region: "近畿地方",
    season: "神戸散歩の春秋",
    budget: "24,000円前後",
    highlight: "港町の空気、城崎温泉、淡路島と、ひとつの県で旅の表情がかなり変わります。",
    x: 0.45,
    y: 0.56,
    areas: ["関西"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["都市観光", "温泉", "グルメ"],
  },
  {
    prefecture: "奈良県",
    region: "近畿地方",
    season: "新緑の春としっとりした秋",
    budget: "20,000円前後",
    highlight: "鹿と古寺に囲まれて、静かに深呼吸したくなる時間が流れます。",
    x: 0.54,
    y: 0.6,
    areas: ["関西"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["歴史・文化", "自然"],
  },
  {
    prefecture: "和歌山県",
    region: "近畿地方",
    season: "海と山の表情が豊かな春秋",
    budget: "24,000円前後",
    highlight: "熊野古道の神秘と白浜の開放感で、心を切り替える旅に向いています。",
    x: 0.52,
    y: 0.65,
    areas: ["関西"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "温泉", "歴史・文化"],
  },
  {
    prefecture: "鳥取県",
    region: "中国地方",
    season: "砂丘の風が心地よい春と秋",
    budget: "21,000円前後",
    highlight: "砂丘の非日常感とカニ・梨の名物で、コンパクトに満足度が高い県です。",
    x: 0.4,
    y: 0.55,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
  {
    prefecture: "島根県",
    region: "中国地方",
    season: "神社めぐりが映える秋",
    budget: "24,000円前後",
    highlight: "出雲大社の空気感と宍道湖の夕景で、静かな余韻が残る旅になります。",
    x: 0.32,
    y: 0.54,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "自然"],
  },
  {
    prefecture: "岡山県",
    region: "中国地方",
    season: "晴れの日が多い春と秋",
    budget: "22,000円前後",
    highlight: "倉敷美観地区の白壁と瀬戸内の穏やかな景色が穏やかにつながります。",
    x: 0.42,
    y: 0.6,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日"],
    styleTags: ["歴史・文化", "グルメ", "都市観光"],
  },
  {
    prefecture: "広島県",
    region: "中国地方",
    season: "春の宮島と秋のしまなみ海道",
    budget: "24,000円前後",
    highlight: "厳島神社の景色とお好み焼き、尾道の坂道散歩が全部強いです。",
    x: 0.36,
    y: 0.6,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "グルメ", "自然"],
  },
  {
    prefecture: "山口県",
    region: "中国地方",
    season: "海風が気持ちいい春秋",
    budget: "23,000円前後",
    highlight: "角島大橋の海色と下関グルメで、爽快な西の玄関口らしさを味わえます。",
    x: 0.26,
    y: 0.6,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
  {
    prefecture: "徳島県",
    region: "四国地方",
    season: "阿波おどりの夏",
    budget: "22,000円前後",
    highlight: "鳴門の渦潮と阿波文化の熱量で、動きのある旅が楽しめます。",
    x: 0.49,
    y: 0.67,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日"],
    styleTags: ["アクティビティ", "歴史・文化", "自然"],
  },
  {
    prefecture: "香川県",
    region: "四国地方",
    season: "うどん巡りしやすい通年",
    budget: "20,000円前後",
    highlight: "島旅とうどんの軽やかさがちょうどよく、ふらっと旅に向いています。",
    x: 0.44,
    y: 0.65,
    areas: ["中国・四国"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "自然", "アクティビティ"],
  },
  {
    prefecture: "愛媛県",
    region: "四国地方",
    season: "道後温泉が気持ちいい秋冬",
    budget: "23,000円前後",
    highlight: "レトロな温泉街としまなみ海道の景色がやさしくつながります。",
    x: 0.35,
    y: 0.68,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["温泉", "自然", "都市観光"],
  },
  {
    prefecture: "高知県",
    region: "四国地方",
    season: "青い海が映える夏",
    budget: "24,000円前後",
    highlight: "仁淀ブルーやカツオのたたきなど、鮮烈な体験が残りやすい県です。",
    x: 0.42,
    y: 0.71,
    areas: ["中国・四国"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
  {
    prefecture: "福岡県",
    region: "九州地方",
    season: "屋台が気持ちいい春と秋",
    budget: "23,000円前後",
    highlight: "博多グルメと門司港レトロで、テンポのいい都市旅が楽しめます。",
    x: 0.23,
    y: 0.68,
    areas: ["九州"],
    budgetTags: ["2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "都市観光", "歴史・文化"],
  },
  {
    prefecture: "佐賀県",
    region: "九州地方",
    season: "器めぐりが楽しい秋",
    budget: "19,000円前後",
    highlight: "有田焼や呼子のいかなど、渋さとごちそうのバランスが良い県です。",
    x: 0.18,
    y: 0.7,
    areas: ["九州"],
    budgetTags: ["〜2万", "2〜5万"],
    durationTags: ["日帰り", "1泊2日"],
    styleTags: ["グルメ", "歴史・文化"],
  },
  {
    prefecture: "長崎県",
    region: "九州地方",
    season: "異国情緒が際立つ春秋",
    budget: "24,000円前後",
    highlight: "坂の街と海景、異文化の歴史が重なって歩くだけでも濃密です。",
    x: 0.12,
    y: 0.71,
    areas: ["九州"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["歴史・文化", "都市観光", "グルメ"],
  },
  {
    prefecture: "熊本県",
    region: "九州地方",
    season: "阿蘇が気持ちいい春から初夏",
    budget: "24,000円前後",
    highlight: "阿蘇の大地の広がりと温泉地のくつろぎで、心身ともにほどけます。",
    x: 0.21,
    y: 0.76,
    areas: ["九州"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "温泉", "アクティビティ"],
  },
  {
    prefecture: "大分県",
    region: "九州地方",
    season: "温泉街が映える通年",
    budget: "25,000円前後",
    highlight: "別府と由布院の二大温泉を軸に、ご褒美感たっぷりの旅ができます。",
    x: 0.28,
    y: 0.74,
    areas: ["九州"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["温泉", "グルメ", "自然"],
  },
  {
    prefecture: "宮崎県",
    region: "九州地方",
    season: "南国ムードの春と夏",
    budget: "24,000円前後",
    highlight: "高千穂の神話世界と日南海岸の明るさが一緒に楽しめます。",
    x: 0.27,
    y: 0.81,
    areas: ["九州"],
    budgetTags: ["2〜5万"],
    durationTags: ["1泊2日", "2泊3日"],
    styleTags: ["自然", "歴史・文化", "アクティビティ"],
  },
  {
    prefecture: "鹿児島県",
    region: "九州地方",
    season: "桜島が映える冬から春",
    budget: "27,000円前後",
    highlight: "火山景観、黒豚グルメ、指宿の砂むし温泉まで個性がぎゅっと濃いです。",
    x: 0.19,
    y: 0.85,
    areas: ["九州"],
    budgetTags: ["2〜5万", "5万〜"],
    durationTags: ["2泊3日", "それ以上"],
    styleTags: ["温泉", "グルメ", "自然"],
  },
  {
    prefecture: "沖縄県",
    region: "沖縄地方",
    season: "海がきれいな春から初夏",
    budget: "55,000円前後",
    highlight: "青い海とゆるやかな島時間で、気分をまるごと切り替えられます。",
    x: 0.12,
    y: 0.94,
    areas: ["沖縄"],
    budgetTags: ["5万〜"],
    durationTags: ["2泊3日", "それ以上"],
    styleTags: ["自然", "グルメ", "アクティビティ"],
  },
];

export function findDestinationByPrefecture(prefecture: string) {
  return destinations.find((destination) => destination.prefecture === prefecture);
}
