export type PrefectureMeta = {
  prefecture: string;
  capital: string;
  latitude: number;
  longitude: number;
  railHub: string;
  featuredArea: string;
  airportCode?: string;
  airportName?: string;
};

export const PREFECTURE_META: Record<string, PrefectureMeta> = {
  北海道: {
    prefecture: "北海道",
    capital: "札幌",
    latitude: 43.0618,
    longitude: 141.3545,
    railHub: "札幌駅",
    featuredArea: "小樽・運河周辺",
    airportCode: "CTS",
    airportName: "新千歳空港",
  },
  青森県: {
    prefecture: "青森県",
    capital: "青森",
    latitude: 40.8222,
    longitude: 140.7474,
    railHub: "新青森駅",
    featuredArea: "弘前公園周辺",
    airportCode: "AOJ",
    airportName: "青森空港",
  },
  岩手県: {
    prefecture: "岩手県",
    capital: "盛岡",
    latitude: 39.7036,
    longitude: 141.1527,
    railHub: "盛岡駅",
    featuredArea: "平泉・中尊寺エリア",
    airportCode: "HNA",
    airportName: "いわて花巻空港",
  },
  宮城県: {
    prefecture: "宮城県",
    capital: "仙台",
    latitude: 38.2682,
    longitude: 140.8694,
    railHub: "仙台駅",
    featuredArea: "松島海岸エリア",
    airportCode: "SDJ",
    airportName: "仙台空港",
  },
  秋田県: {
    prefecture: "秋田県",
    capital: "秋田",
    latitude: 39.7186,
    longitude: 140.1024,
    railHub: "秋田駅",
    featuredArea: "乳頭温泉郷",
    airportCode: "AXT",
    airportName: "秋田空港",
  },
  山形県: {
    prefecture: "山形県",
    capital: "山形",
    latitude: 38.2404,
    longitude: 140.3633,
    railHub: "山形駅",
    featuredArea: "蔵王温泉エリア",
    airportCode: "GAJ",
    airportName: "山形空港",
  },
  福島県: {
    prefecture: "福島県",
    capital: "福島",
    latitude: 37.7608,
    longitude: 140.4747,
    railHub: "福島駅",
    featuredArea: "会津若松エリア",
    airportCode: "FKS",
    airportName: "福島空港",
  },
  茨城県: {
    prefecture: "茨城県",
    capital: "水戸",
    latitude: 36.3659,
    longitude: 140.4711,
    railHub: "水戸駅",
    featuredArea: "ひたち海浜公園周辺",
    airportCode: "IBR",
    airportName: "茨城空港",
  },
  栃木県: {
    prefecture: "栃木県",
    capital: "宇都宮",
    latitude: 36.5551,
    longitude: 139.8828,
    railHub: "宇都宮駅",
    featuredArea: "日光東照宮エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  群馬県: {
    prefecture: "群馬県",
    capital: "前橋",
    latitude: 36.3895,
    longitude: 139.0634,
    railHub: "高崎駅",
    featuredArea: "草津温泉エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  埼玉県: {
    prefecture: "埼玉県",
    capital: "さいたま",
    latitude: 35.8617,
    longitude: 139.6455,
    railHub: "大宮駅",
    featuredArea: "川越・蔵造りの町並み",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  千葉県: {
    prefecture: "千葉県",
    capital: "千葉",
    latitude: 35.6074,
    longitude: 140.1065,
    railHub: "千葉駅",
    featuredArea: "館山・南房総エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  東京都: {
    prefecture: "東京都",
    capital: "東京",
    latitude: 35.6762,
    longitude: 139.6503,
    railHub: "東京駅",
    featuredArea: "浅草・上野エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  神奈川県: {
    prefecture: "神奈川県",
    capital: "横浜",
    latitude: 35.4437,
    longitude: 139.638,
    railHub: "横浜駅",
    featuredArea: "箱根湯本エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  新潟県: {
    prefecture: "新潟県",
    capital: "新潟",
    latitude: 37.9022,
    longitude: 139.0232,
    railHub: "新潟駅",
    featuredArea: "越後湯沢エリア",
    airportCode: "KIJ",
    airportName: "新潟空港",
  },
  富山県: {
    prefecture: "富山県",
    capital: "富山",
    latitude: 36.6953,
    longitude: 137.2113,
    railHub: "富山駅",
    featuredArea: "立山黒部アルペンルート周辺",
    airportCode: "TOY",
    airportName: "富山空港",
  },
  石川県: {
    prefecture: "石川県",
    capital: "金沢",
    latitude: 36.5947,
    longitude: 136.6256,
    railHub: "金沢駅",
    featuredArea: "加賀温泉郷",
    airportCode: "KMQ",
    airportName: "小松空港",
  },
  福井県: {
    prefecture: "福井県",
    capital: "福井",
    latitude: 36.0652,
    longitude: 136.2216,
    railHub: "福井駅",
    featuredArea: "東尋坊エリア",
    airportCode: "KMQ",
    airportName: "小松空港",
  },
  山梨県: {
    prefecture: "山梨県",
    capital: "甲府",
    latitude: 35.6639,
    longitude: 138.5684,
    railHub: "甲府駅",
    featuredArea: "河口湖エリア",
    airportCode: "TYO",
    airportName: "東京エリア空港",
  },
  長野県: {
    prefecture: "長野県",
    capital: "長野",
    latitude: 36.6513,
    longitude: 138.181,
    railHub: "長野駅",
    featuredArea: "上高地・松本エリア",
    airportCode: "MMJ",
    airportName: "松本空港",
  },
  岐阜県: {
    prefecture: "岐阜県",
    capital: "岐阜",
    latitude: 35.4233,
    longitude: 136.7607,
    railHub: "岐阜駅",
    featuredArea: "飛騨高山エリア",
    airportCode: "NGO",
    airportName: "中部国際空港",
  },
  静岡県: {
    prefecture: "静岡県",
    capital: "静岡",
    latitude: 34.9756,
    longitude: 138.3828,
    railHub: "静岡駅",
    featuredArea: "熱海・伊東エリア",
    airportCode: "FSZ",
    airportName: "富士山静岡空港",
  },
  愛知県: {
    prefecture: "愛知県",
    capital: "名古屋",
    latitude: 35.1815,
    longitude: 136.9066,
    railHub: "名古屋駅",
    featuredArea: "犬山・城下町エリア",
    airportCode: "NGO",
    airportName: "中部国際空港",
  },
  三重県: {
    prefecture: "三重県",
    capital: "津",
    latitude: 34.7303,
    longitude: 136.5086,
    railHub: "津駅",
    featuredArea: "伊勢志摩エリア",
    airportCode: "NGO",
    airportName: "中部国際空港",
  },
  滋賀県: {
    prefecture: "滋賀県",
    capital: "大津",
    latitude: 35.0179,
    longitude: 135.8546,
    railHub: "大津駅",
    featuredArea: "彦根城エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  京都府: {
    prefecture: "京都府",
    capital: "京都",
    latitude: 35.0116,
    longitude: 135.7681,
    railHub: "京都駅",
    featuredArea: "嵐山エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  大阪府: {
    prefecture: "大阪府",
    capital: "大阪",
    latitude: 34.6937,
    longitude: 135.5023,
    railHub: "新大阪駅",
    featuredArea: "なんば・道頓堀エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  兵庫県: {
    prefecture: "兵庫県",
    capital: "神戸",
    latitude: 34.6901,
    longitude: 135.1955,
    railHub: "三ノ宮駅",
    featuredArea: "城崎温泉エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  奈良県: {
    prefecture: "奈良県",
    capital: "奈良",
    latitude: 34.6851,
    longitude: 135.8048,
    railHub: "奈良駅",
    featuredArea: "吉野山エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  和歌山県: {
    prefecture: "和歌山県",
    capital: "和歌山",
    latitude: 34.226,
    longitude: 135.1675,
    railHub: "和歌山駅",
    featuredArea: "白浜温泉エリア",
    airportCode: "OSA",
    airportName: "大阪エリア空港",
  },
  鳥取県: {
    prefecture: "鳥取県",
    capital: "鳥取",
    latitude: 35.5011,
    longitude: 134.2351,
    railHub: "鳥取駅",
    featuredArea: "皆生温泉エリア",
    airportCode: "TTJ",
    airportName: "鳥取砂丘コナン空港",
  },
  島根県: {
    prefecture: "島根県",
    capital: "松江",
    latitude: 35.4681,
    longitude: 133.0484,
    railHub: "松江駅",
    featuredArea: "出雲大社エリア",
    airportCode: "IZO",
    airportName: "出雲空港",
  },
  岡山県: {
    prefecture: "岡山県",
    capital: "岡山",
    latitude: 34.6551,
    longitude: 133.9195,
    railHub: "岡山駅",
    featuredArea: "倉敷美観地区",
    airportCode: "OKJ",
    airportName: "岡山桃太郎空港",
  },
  広島県: {
    prefecture: "広島県",
    capital: "広島",
    latitude: 34.3853,
    longitude: 132.4553,
    railHub: "広島駅",
    featuredArea: "宮島口エリア",
    airportCode: "HIJ",
    airportName: "広島空港",
  },
  山口県: {
    prefecture: "山口県",
    capital: "山口",
    latitude: 34.1785,
    longitude: 131.4737,
    railHub: "新山口駅",
    featuredArea: "下関・唐戸エリア",
    airportCode: "UBJ",
    airportName: "山口宇部空港",
  },
  徳島県: {
    prefecture: "徳島県",
    capital: "徳島",
    latitude: 34.0703,
    longitude: 134.5548,
    railHub: "徳島駅",
    featuredArea: "鳴門海峡エリア",
    airportCode: "TKS",
    airportName: "徳島阿波おどり空港",
  },
  香川県: {
    prefecture: "香川県",
    capital: "高松",
    latitude: 34.3428,
    longitude: 134.0466,
    railHub: "高松駅",
    featuredArea: "こんぴらさんエリア",
    airportCode: "TAK",
    airportName: "高松空港",
  },
  愛媛県: {
    prefecture: "愛媛県",
    capital: "松山",
    latitude: 33.8392,
    longitude: 132.7657,
    railHub: "松山駅",
    featuredArea: "道後温泉エリア",
    airportCode: "MYJ",
    airportName: "松山空港",
  },
  高知県: {
    prefecture: "高知県",
    capital: "高知",
    latitude: 33.5597,
    longitude: 133.5311,
    railHub: "高知駅",
    featuredArea: "四万十川エリア",
    airportCode: "KCZ",
    airportName: "高知龍馬空港",
  },
  福岡県: {
    prefecture: "福岡県",
    capital: "福岡",
    latitude: 33.5904,
    longitude: 130.4017,
    railHub: "博多駅",
    featuredArea: "中洲・天神エリア",
    airportCode: "FUK",
    airportName: "福岡空港",
  },
  佐賀県: {
    prefecture: "佐賀県",
    capital: "佐賀",
    latitude: 33.2494,
    longitude: 130.2988,
    railHub: "佐賀駅",
    featuredArea: "嬉野温泉エリア",
    airportCode: "HSG",
    airportName: "佐賀空港",
  },
  長崎県: {
    prefecture: "長崎県",
    capital: "長崎",
    latitude: 32.7503,
    longitude: 129.8777,
    railHub: "長崎駅",
    featuredArea: "ハウステンボス周辺",
    airportCode: "NGS",
    airportName: "長崎空港",
  },
  熊本県: {
    prefecture: "熊本県",
    capital: "熊本",
    latitude: 32.8031,
    longitude: 130.7079,
    railHub: "熊本駅",
    featuredArea: "阿蘇・黒川温泉エリア",
    airportCode: "KMJ",
    airportName: "熊本空港",
  },
  大分県: {
    prefecture: "大分県",
    capital: "大分",
    latitude: 33.2396,
    longitude: 131.6093,
    railHub: "別府駅",
    featuredArea: "由布院エリア",
    airportCode: "OIT",
    airportName: "大分空港",
  },
  宮崎県: {
    prefecture: "宮崎県",
    capital: "宮崎",
    latitude: 31.9111,
    longitude: 131.4239,
    railHub: "宮崎駅",
    featuredArea: "高千穂エリア",
    airportCode: "KMI",
    airportName: "宮崎空港",
  },
  鹿児島県: {
    prefecture: "鹿児島県",
    capital: "鹿児島",
    latitude: 31.5602,
    longitude: 130.5581,
    railHub: "鹿児島中央駅",
    featuredArea: "指宿温泉エリア",
    airportCode: "KOJ",
    airportName: "鹿児島空港",
  },
  沖縄県: {
    prefecture: "沖縄県",
    capital: "那覇",
    latitude: 26.2124,
    longitude: 127.6809,
    railHub: "県庁前駅",
    featuredArea: "恩納村リゾートエリア",
    airportCode: "OKA",
    airportName: "那覇空港",
  },
};

export function getPrefectureMeta(prefecture: string) {
  return PREFECTURE_META[prefecture];
}
